#!/system/bin/sh
#
# Sapphire ROM Startup Script
# Call depmod and setup our modprobe environment
#
# Copyright (C) 2010 Austen Dicken (cvpcs)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

DEPMOD="$(busybox which depmod)"

# we might as well only bother if we can depmod
if [ ! -z "${DEPMOD}" ] ; then
	# first we clear out any symlinks we have sitting around
	for i in /system/lib/modules/*; do
		if [ -L "${i}" ] ; then
			rm "${i}"
		fi
	done

	# now re-make our symlink for whatever kernel they are currently running
	ln -s ./ "/system/lib/modules/$(uname -r)"

	# and depmod
	"${DEPMOD}"
fi
