#!/bin/bash
#
# Get Build Version
# Determines a build version (build number) for the current build
#
# Copyright (C) <year> Austen Dicken (cvpcs)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

BUILD_VER_FILE="$(dirname "$0")/../products/cvpcs_version_build.mk"

if [ ! -e "${BUILD_VER_FILE}" ] ; then
	exit 1;
fi

# get our values
CUR_BUILD_VER=$(grep -E '^[^#]' "${BUILD_VER_FILE}" \
        | grep build_version_build | sed -r 's/^[^=]+= *([0-9]+)[^0-9]*$/\1/')
INC_BUILD_VER=$(expr ${CUR_BUILD_VER} + 1)

# increment the file
sed -i -r "s/^(.*build_version_build.*:=[^0-9]*)([0-9]+)([^0-9]*)$/\1${INC_BUILD_VER}\3/" \
        "${BUILD_VER_FILE}"

# echo what changed
echo "Current build version: ${CUR_BUILD_VER}"
echo "Next build version: ${INC_BUILD_VER}"
